cwd: "/opt/ublip/rails/current"
port: "8000"
num_procs: "2"
address: "127.0.0.1"
pid_file: "/opt/ublip/rails/current/tmp/pids/mongrel.pid"
log_file: "/opt/ublip/rails/current/log/mongrel.log"
servers: 2
environment: production